### PR TITLE
DEV-132 Migrated plugin to Capacitor 5

### PR DESCRIPTION
**Pull request by fcurzel**

### CODE REVIEW

**Comment by simaxme** [comment]
The capacitor 5 update is very important for updating the current project of my team. Would appreciate a fast merge.

**Comment by JaHollTV** [comment]
any update here?

**Comment by fcurzel** [comment]
Hello!
I'm still running some tests, but you can expect a release in a couple of days!
In the meanwhile, if you need to integrate Glassfy in your apps, you can [target](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#git-urls-as-dependencies) this branch in your package.json

**Comment by alxndr-stlz** [comment]
I just found this request. It would be very useful for me as well.

**Comment by Matz3000-Matti** [comment]
I also need this, please!

**Comment by LexWebDev** [comment]
hello! when can we expect an update?

**Comment by JaHollTV** [comment]
@fcurzel & @lgarbo & @marcopifferi Could you please check this request very, very soon?

**Comment by lgarbo** [comment]
We have just released [version 3.0.0](https://github.com/glassfy/capacitor-plugin-glassfy/releases/tag/3.0.0) that supports Capacitor 5

**Pull request merged**
